Sonarqube for Gradle
bitwarden/passwordless-android pull request #80
Opened 2024-08-05 07:21 UTC by jonashendrickx

### Description

We were missing some configuration for Sonarqube with Gradle.

### Shape

n/a

### Screenshots

n/a

### Checklist
I did the following to ensure that my changes were tested thoroughly:
- __

I did the following to ensure that my changes do not introduce security vulnerabilities:
- __

2024-08-05 12:29 UTC, withinfocus requested changes

2024-08-05 12:29 UTC, withinfocus commented on app/build.gradle.kts
> +        property("sonar.tests", "app/src/test/,passwordless/src/test/")
❌ You should define Sonar inclusions and exclusions too.

2024-08-05 12:29 UTC, withinfocus commented on app/build.gradle.kts
> +}
⛏️ End in a newline.

2024-08-05 12:29 UTC, withinfocus commented on gradle/libs.versions.toml
> +sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
⛏️ Newline.

2024-08-05 12:29 UTC, withinfocus commented on passwordless/build.gradle.kts
> +        property("sonar.tests", "passwordless/src/test/")
❌ Same inclusions and exclusions.

2024-08-09 12:52 UTC, withinfocus requested changes
Just one item I think!

2024-08-09 12:52 UTC, withinfocus commented on app/build.gradle.kts
> +        property("sonar.tests", "app/src/test/,passwordless/src/test/")
🎨 The "passwordless" module wouldn't need to be here since it's listed separately below.

2024-08-09 13:05 UTC, withinfocus approved these changes

2024-08-12 14:00 UTC, jrmccannon approved these changes

2024-08-12 14:00 UTC, merged